Information:
  Title: DevCreates Community Blog
  Icon: icon.png
  Description: DevCreates is a Developer Community that holds the "fire" Discord tag.
  Link: discord.gg/devcreates
  Theme: CatppuccinMocha

Connections:
  GitHub: TheDevCreates
